# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=128, verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe5\x90\x8d\xe7\xa7\xb0')),
                ('platform_desc', models.CharField(max_length=256, null=True, verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'db_table': 'iptv_platform',
                'verbose_name': '\u5e73\u53f0\u8868',
                'verbose_name_plural': '\u5e73\u53f0\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=128, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe5\x90\x8d\xe7\xa7\xb0')),
                ('program_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('status', models.SmallIntegerField(choices=[(b'0', b'off'), (b'1', b'on')], verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe7\x8a\xb6\xe6\x80\x81 0 \xe5\x85\xb3\xe9\x97\xad 1 \xe5\xbc\x80\xe5\x90\xaf')),
                ('strategy', models.CharField(max_length=123)),
            ],
            options={
                'db_table': 'iptv_program',
                'verbose_name': '\u76f4\u64ad\u9891\u9053\u8868',
                'verbose_name_plural': '\u76f4\u64ad\u9891\u9053\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVProgramOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iptv_program_operation_log', to='IPTVStopSystem.IPTVProgram', verbose_name=b'\xe9\xa2\x91\xe9\x81\x93')),
            ],
            options={
                'db_table': 'iptv_program_operation_log',
                'verbose_name': '\u76f4\u64ad\u9891\u9053\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u76f4\u64ad\u9891\u9053\u64cd\u4f5c\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVRouterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=128, verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe8\xb7\xaf\xe7\x94\xb1\xe7\xbb\x84\xe5\x90\x8d\xe7\xa7\xb0')),
                ('router_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe8\xb7\xaf\xe7\x94\xb1\xe7\xbb\x84\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'db_table': 'iptv_router_group',
                'verbose_name': '\u63a7\u5236\u8def\u7531\u7ec4\u8868',
                'verbose_name_plural': '\u63a7\u5236\u8def\u7531\u7ec4\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=128, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('status', models.SmallIntegerField(choices=[(b'0', b'\xe5\xa4\xb1\xe8\xb4\xa5'), (b'1', b'\xe6\x88\x90\xe5\x8a\x9f')], verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\x8a\xb6\xe6\x80\x81')),
                ('router_ip', models.GenericIPAddressField(verbose_name=b'\xe8\xb7\xaf\xe7\x94\xb1\xe8\xae\xbe\xe5\xa4\x87ip')),
                ('system_manager', models.CharField(max_length=128, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xb4\xa3\xe4\xbb\xbb\xe4\xba\xba')),
                ('system_manage_room', models.CharField(max_length=128, null=True, verbose_name=b'\xe8\xb4\xa3\xe4\xbb\xbb\xe7\xa7\x91\xe5\xae\xa4')),
                ('system_attribute', models.CharField(max_length=128, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xb1\x9e\xe6\x80\xa7')),
                ('system_attribute_value', models.CharField(max_length=128, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xb1\x9e\xe6\x80\xa7\xe5\x80\xbc')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPTVStopSystem.IPTVPlatform', verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe8\xa1\xa8')),
                ('router_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPTVStopSystem.IPTVRouterGroup', verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe8\xb7\xaf\xe7\x94\xb1\xe7\xbb\x84\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'db_table': 'iptv_system',
                'verbose_name': '\u8def\u7531\u7cfb\u7edf\u8868',
                'verbose_name_plural': '\u8def\u7531\u7cfb\u7edf\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=256, verbose_name=b'\xe5\x8c\xba\xe5\x9f\x9f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPTVStopSystem.IPTVPlatform', verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0')),
            ],
            options={
                'db_table': 'iptv_zone',
                'verbose_name': '\u533a\u57df\u8868',
                'verbose_name_plural': '\u533a\u57df\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVZoneNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=256, verbose_name=b'\xe5\x8c\xba\xe5\x9f\x9f\xe7\xbb\x93\xe7\x82\xb9\xe5\x90\x8d\xe7\xa7\xb0')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPTVStopSystem.IPTVZone', verbose_name=b'\xe5\x8c\xba\xe5\x9f\x9f')),
            ],
            options={
                'db_table': 'iptv_zone_node',
                'verbose_name': '\u533a\u57df\u7ed3\u70b9\u8868',
                'verbose_name_plural': '\u533a\u57df\u7ed3\u70b9\u8868',
            },
        ),
        migrations.AddField(
            model_name='iptvprogram',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iptv_program', to='IPTVStopSystem.IPTVRouterGroup', verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe8\xb7\xaf\xe7\x94\xb1\xe7\xbb\x84'),
        ),
    ]
