# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptvprogram',
            name='program_ip',
            field=models.CharField(default=datetime.datetime(2018, 5, 29, 2, 50, 9, 42683, tzinfo=utc), max_length=128, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93ip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'off'), (b'2', b'on')], verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe7\x8a\xb6\xe6\x80\x81 0 \xe5\x85\xb3\xe9\x97\xad 1 \xe5\xbc\x80\xe5\x90\xaf'),
        ),
        migrations.AlterField(
            model_name='iptvsystem',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\xa4\xb1\xe8\xb4\xa5'), (b'2', b'\xe6\x88\x90\xe5\x8a\x9f')], verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
