# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0002_auto_20180529_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVCDNOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\x86\x85\xe5\xae\xb9')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'iptv_cdn_operation_log',
                'verbose_name': 'CDN\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': 'CDN\u64cd\u4f5c\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='IPTVEPGOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\x86\x85\xe5\xae\xb9')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'iptv_epg_operation_log',
                'verbose_name': 'EPG\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': 'EPG\u64cd\u4f5c\u65e5\u5fd7\u8868',
            },
        ),
        migrations.AddField(
            model_name='iptvprogramoperationlog',
            name='content',
            field=models.TextField(default=datetime.datetime(2018, 5, 30, 6, 15, 57, 411069, tzinfo=utc), verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\x86\x85\xe5\xae\xb9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iptvsystem',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\xa4\xb1\xe8\xb4\xa5'), (b'2', b'\xe6\x88\x90\xe5\x8a\x9f')], verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xbb\x93\xe6\x9e\x9c'),
        ),
        migrations.AddField(
            model_name='iptvepgoperationlog',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iptv_epg_operation_log', to='IPTVStopSystem.IPTVSystem', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
        migrations.AddField(
            model_name='iptvcdnoperationlog',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iptv_cdn_operation_log', to='IPTVStopSystem.IPTVSystem', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
    ]
