# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0003_auto_20180530_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVProcessVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.SmallIntegerField(choices=[(b'1', b'EPG\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe7\x9b\xb4\xe6\x92\xad\xe9\xa2\x91\xe9\x81\x93\xe5\x85\xb3\xe5\x81\x9c'), (b'3', b'CDN\xe5\x85\xb3\xe5\x81\x9c')], verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb1\xbb\xe5\x9e\x8b 1:EPG\xe5\x85\xb3\xe5\x81\x9c 2:\xe7\x9b\xb4\xe6\x92\xad\xe9\xa2\x91\xe9\x81\x93\xe5\x85\xb3\xe5\x81\x9c 3:CDN\xe5\x85\xb3\xe5\x81\x9c')),
                ('operation_target', models.CharField(max_length=256, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\xaf\xb9\xe8\xb1\xa1')),
                ('status', models.SmallIntegerField(choices=[(b'0', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'1', b'\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87'), (b'2', b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad')], verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x8c0:\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87 1:\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87 2:\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x84\x8f\xe8\xa7\x81')),
            ],
            options={
                'db_table': 'iptv_process_verify',
                'verbose_name': '\u6d41\u7a0b\u5ba1\u6279\u8868',
                'verbose_name_plural': '\u6d41\u7a0b\u5ba1\u6279\u8868',
            },
        ),
    ]
