# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0004_iptvprocessverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptvprogram',
            name='program_desc',
        ),
        migrations.RemoveField(
            model_name='iptvprogram',
            name='router',
        ),
        migrations.RemoveField(
            model_name='iptvprogram',
            name='strategy',
        ),
        migrations.AddField(
            model_name='iptvprogram',
            name='program_num',
            field=models.CharField(default=1, max_length=128, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe5\x8f\xb7'),
            preserve_default=False,
        ),
    ]
