# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0005_auto_20180604_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVCDNNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0(\xe4\xb8\xad\xe5\x85\xb4 / \xe5\x8d\x8e\xe4\xb8\xba)')),
                ('city', models.CharField(max_length=128, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x9c\xb0\xe5\xb8\x82')),
                ('node_name', models.CharField(max_length=128, verbose_name=b'\xe8\x8a\x82\xe7\x82\xb9\xe5\x90\x8d\xe7\xa7\xb0')),
                ('status', models.SmallIntegerField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe6\xad\xa3\xe5\xb8\xb8')], verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'iptv_cdn_node',
                'verbose_name': 'CDN\u8282\u70b9\u8868',
                'verbose_name_plural': 'CDN\u8282\u70b9\u8868',
            },
        ),
        migrations.RemoveField(
            model_name='iptvepgoperationlog',
            name='system',
        ),
        migrations.RemoveField(
            model_name='iptvsystem',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='iptvsystem',
            name='router_group',
        ),
        migrations.RemoveField(
            model_name='iptvzone',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='iptvzonenode',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='iptvcdnoperationlog',
            name='system',
        ),
        migrations.AlterField(
            model_name='iptvprocessverify',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'2', b'\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87'), (b'3', b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad')], verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x8c1:\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87 2:\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87 3:\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_num',
            field=models.IntegerField(verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe6\xad\xa3\xe5\xb8\xb8')], verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe7\x8a\xb6\xe6\x80\x81 1 \xe5\x85\xb3\xe5\x81\x9c 2 \xe6\xad\xa3\xe5\xb8\xb8'),
        ),
        migrations.DeleteModel(
            name='IPTVEPGOperationLog',
        ),
        migrations.DeleteModel(
            name='IPTVPlatform',
        ),
        migrations.DeleteModel(
            name='IPTVRouterGroup',
        ),
        migrations.DeleteModel(
            name='IPTVSystem',
        ),
        migrations.DeleteModel(
            name='IPTVZone',
        ),
        migrations.DeleteModel(
            name='IPTVZoneNode',
        ),
        migrations.AddField(
            model_name='iptvcdnoperationlog',
            name='cdn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='iptv_cdn_operation_log', to='IPTVStopSystem.IPTVCDNNode', verbose_name=b'CDN\xe8\x8a\x82\xe7\x82\xb9'),
            preserve_default=False,
        ),
    ]
