# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0006_auto_20180604_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptvprocessverify',
            name='status',
        ),
    ]
