# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0007_remove_iptvprocessverify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptvprocessverify',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'2', b'\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87'), (b'3', b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad')], default=3, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x8c1:\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87 2:\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87 3:\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad'),
            preserve_default=False,
        ),
    ]
