# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0008_iptvprocessverify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptvprocessverify',
            name='operation',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe6\x81\xa2\xe5\xa4\x8d')], default=1, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c 1 \xe5\x85\xb3\xe5\x81\x9c 2 \xe6\x81\xa2\xe5\xa4\x8d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iptvprocessverify',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad'), (b'2', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'3', b'\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87')], verbose_name=b'\xe5\xae\xa1\xe6\xa0\xb8\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x8c1:\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad 2:\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87 3:\xe5\xb7\xb2\xe9\x80\x9a\xe8\xbf\x87'),
        ),
    ]
