# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0009_auto_20180604_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptvprocessverify',
            name='operation',
        ),
        migrations.AddField(
            model_name='iptvprocessverify',
            name='process_type',
            field=models.SmallIntegerField(choices=[(b'1', b'EPG\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe7\x9b\xb4\xe6\x92\xad\xe9\xa2\x91\xe9\x81\x93\xe5\x85\xb3\xe5\x81\x9c'), (b'3', b'CDN\xe5\x85\xb3\xe5\x81\x9c')], default=1, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb1\xbb\xe5\x9e\x8b 1:EPG\xe5\x85\xb3\xe5\x81\x9c 2:\xe7\x9b\xb4\xe6\x92\xad\xe9\xa2\x91\xe9\x81\x93\xe5\x85\xb3\xe5\x81\x9c 3:CDN\xe5\x85\xb3\xe5\x81\x9c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iptvprocessverify',
            name='operation_type',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe6\x81\xa2\xe5\xa4\x8d')], verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c 1 \xe5\x85\xb3\xe5\x81\x9c 2 \xe6\x81\xa2\xe5\xa4\x8d'),
        ),
    ]
