# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0011_auto_20180606_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_ip',
            field=models.CharField(max_length=256, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93ip'),
        ),
    ]
