# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0012_auto_20180606_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptvprogram',
            name='platform',
            field=models.CharField(max_length=30, verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_ip_type',
            field=models.CharField(max_length=50, verbose_name=b'ip\xe5\x9c\xb0\xe5\x9d\x80\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_type',
            field=models.CharField(max_length=30, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
