# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0013_auto_20180606_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPTVProcessVerify',
        ),
    ]
