# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0014_delete_iptvprocessverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVEPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe5\xbc\x80\xe5\x90\xaf')], verbose_name=b'EPG\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'iptv_epg',
                'verbose_name': 'EPG\u8868',
                'verbose_name_plural': 'EPG\u8868',
            },
        ),
    ]
