# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0016_auto_20180608_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptvepg',
            name='status',
            field=models.SmallIntegerField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe5\xbc\x80\xe5\x90\xaf')], verbose_name=b'EPG\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
