# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0017_auto_20180611_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptvprogram',
            name='program_num',
            field=models.IntegerField(default=1, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe5\x8f\xb7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='platform',
            field=models.CharField(max_length=30, null=True, verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_ip',
            field=models.CharField(max_length=256, null=True, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93ip'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_ip_type',
            field=models.CharField(max_length=50, null=True, verbose_name=b'ip\xe5\x9c\xb0\xe5\x9d\x80\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_name',
            field=models.CharField(max_length=128, null=True, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_type',
            field=models.CharField(max_length=30, null=True, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='iptvprogramoperationlog',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iptv_program_operation_log', to='IPTVStopSystem.IPTVProgram', verbose_name=b'\xe9\xa2\x91\xe9\x81\x93'),
        ),
    ]
