# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0018_auto_20180615_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptvprogram',
            name='program_num',
            field=models.CharField(max_length=128, null=True, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe5\x8f\xb7'),
        ),
    ]
