# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTVStopSystem', '0021_iptvcdnnode_paltform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptvprogram',
            name='status',
            field=models.CharField(choices=[(b'1', b'\xe5\x85\xb3\xe5\x81\x9c'), (b'2', b'\xe6\xad\xa3\xe5\xb8\xb8')], max_length=50, verbose_name=b'\xe9\xa2\x91\xe9\x81\x93\xe7\x8a\xb6\xe6\x80\x81 1 \xe5\x85\xb3\xe5\x81\x9c 2 \xe6\xad\xa3\xe5\xb8\xb8'),
        ),
    ]
